### PR TITLE
Decide if swipe change the active item

### PR DESCRIPTION
**Pull request by Jeff0029**
Small bool that decides if swiping changes the active item, does not change the default behavior.

### CODE REVIEW

**Comment by nir9** [comment]
Why do you need a special option for this if you can just decide not to do anything with the active class in your css?

**Comment by Jeff0029** [comment]
Because it still triggers the event "changeActiveIndex" which I use to toggle hidden divs.

**Comment by nir9** [comment]
I still don't get why you need a special option for this you can just ignore the "changeActiveIndex" event if you want and likewise to the active item class...

**Comment by Jeff0029** [comment]
It's because at that level I'd have to install another plugin to recognize what is a swipe and what is a touch like hammer.js (unless you have something like a public enum that tells us the type of motion captured).

Setting a simple bool seemed like a efficient solution.  But if you really don't want an extra bool in your settings for something that seems useless, my company can just use my forked repo instead.

**Comment by nir9** [comment]
Well you can use the clickSlide to recognize when tapping a slide.
And the changeActiveIndex event when the active slide changes...
More info in the docs: http://itemslide.github.io/docs/

**Comment by Jeff0029** [comment]
I just notice my recent push went on this merge request.  Still new to this so now I would say this pull request is a bad idea.

**Pull request closed without merging**
