### PR TITLE
Issues 41- loop feature

### PR DESCRIPTION
**Pull request by jetelusmaximus**
Hello I would like to contribute with loop feature described in issue #41
Thanks for merge.

### CODE REVIEW

**Comment by jetelusmaximus** [comment]
Let me know please if it's ok :)

**Comment by nir9** [comment]
Hi, changing the landing slide index when swiping beyond the end will make the sliding non continuous because when reaching the end and swiping further it will seem like there's no more and when letting go it will all the sudden jump to the first slide for example.

You need it to feel continuous - a way to implement this feature is to reposition the first slide to be after the last slide when arriving to the last slide and then when arriving to the first slide again repositioning the second slide to be after the first slide and so on.

Good luck!

**Comment by PurHur** [comment]
Note that the reposition concept is used widely in mostly all sliders.

**Comment by nir9** [comment]
Closing due to no activity

**Pull request closed without merging**
