### PR TITLE
Project structure updated. Destroy method inserted. Align setting created.

### PR DESCRIPTION
**Pull request by AlexVvx**
Hello, I refactored a little bit my previous update: align setting created and slider looks similar to prev version. It is possible to run slider with align: justify.

### CODE REVIEW

**Comment by nir9** [comment]
Ok so the align has indeed been fixed thanks, but there are still some small problems that need to be fixed before merge:
- Mouse scrolling doesn't work.
- And the swipe out animation doesn't work.

**Comment by AlexVvx** [comment]
I fixed mouse scrolling, but can't figure out what's wrong with swipe out animation. Can you please help me to fix animation?

**Comment by nir9** [comment]
Sure i'll take a look and see if i can fix it.

**Comment by nir9** [comment]
Ok so i found the problem turns out it's just a was just a small issue, so i'm going to merge your pull request and fix the problem right away.
Anyways thanks for the great contribution!

**Pull request merged**
